nelmio_api_doc:
    documentation:
        info:
            title: Book App
            description:
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/book(?s) # Accepts routes under /api except /api/doc
