monolog:
  handlers:

    console:
      type: stream
      path: php://stdout
      level: critical
    file_log:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ~
    app_log:
      type: stream
      path: "%kernel.logs_dir%/app.log"
      level: info
      channels: [app]
